training = False
creatingClusters = False
creatingActivitySequence = False
numberOfClubsters = 0
# activity = 'Jumping Jax'
# activity = 'Waving left hand'
# activity = 'DAPT'
# activity = 'Jumping'
activity = ''
activityDetected=''