training = False
creatingClusters = False
creatingActivitySequence = True
numberOfClubsters = 5
# activity = 'Jumping Jax'
# activity = 'Waving left hand'
# activity = 'DAPT'
# activity = 'Jumping'
activity = 'Squats'