words = [
{'ptscs': 'Biceps Curl'},
{'tptsc': 'Biceps Curl'},
{'cstpt': 'Biceps Curl'},
{'scstp': 'Biceps Curl'},
{'tpxpi': 'Biceps Curl'},
{'dlmgm': 'Dumbbell Shoulder Press'},
{'mldlm': 'Dumbbell Shoulder Press'},
{'mgmld': 'Dumbbell Shoulder Press'},
{'gmldl': 'Dumbbell Shoulder Press'},
{'ldlmg': 'Dumbbell Shoulder Press'},
{'lmgml': 'Dumbbell Shoulder Press'},
{'ayaya': 'Jumping'},
{'yuyax': 'Jumping'},
{'uxuax': 'Jumping'},
{'uyxau': 'Jumping'},
{'uvxvy': 'Jumping'},
{'yvxvy': 'Jumping'},
{'yvxyx': 'Jumping'},
{'xyvxy': 'Jumping'},
{'yxvuy': 'Jumping'},
{'xyuxv': 'Jumping'},
{'yuxvy': 'Jumping'},
{'xuxyu': 'Jumping'},
{'yxyux': 'Jumping'},
{'xyxyu': 'Jumping'},
{'auyvh': 'Jumping Jacks'},
{'jfbjh': 'Jumping Jacks'},
{'whjfb': 'Jumping Jacks'},
{'fjhvw': 'Jumping Jacks'},
{'jfbfj': 'Jumping Jacks'},
{'vwhjf': 'Jumping Jacks'},
{'bfhwv': 'Jumping Jacks'},
{'hjbfj': 'Jumping Jacks'},
{'fjhwv': 'Jumping Jacks'},
{'bjhwv': 'Jumping Jacks'},
{'hjfbf': 'Jumping Jacks'},
{'hwhjf': 'Jumping Jacks'},
{'bjwhj': 'Jumping Jacks'},
{'fjhwh': 'Jumping Jacks'},
{'fbfju': 'Jumping Jacks'},
{'jhwhj': 'Jumping Jacks'},
{'fbfjh': 'Jumping Jacks'},
{'whjfj': 'Jumping Jacks'},
{'scqer': 'Squats'},
{'reqer': 'Squats'},
{'renqe': 'Squats'},
{'ereqe': 'Squats'},
{'rereq': 'Squats'}

]


